# netlify.toml
[functions]
  # Indica a Netlify que las funciones están en la carpeta netlify/functions
  directory = "netlify/functions"
  
# Esto es opcional, pero ayuda a que la URL de la función sea más "limpia"
[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate-hashtags"
  status = 200